version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
      - ./code/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: ps01
