# Generated by Django 2.0.6 on 2018-06-09 21:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bokning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referens', models.IntegerField(blank=True)),
                ('pumpStr', models.IntegerField(blank=True)),
                ('slangStr', models.IntegerField(blank=True)),
                ('pump', models.IntegerField(blank=True)),
                ('maskinist', models.CharField(blank=True, max_length=124)),
                ('betongLev', models.CharField(blank=True, max_length=124)),
                ('betongKvalite', models.CharField(blank=True, max_length=124)),
                ('bestalld', models.IntegerField(blank=True)),
                ('pumpMng', models.IntegerField()),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('littNr', models.IntegerField()),
                ('arbNr', models.IntegerField(blank=True)),
                ('resTid', models.IntegerField()),
                ('grundavgift', models.IntegerField()),
                ('pumpStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('pumpSlut', models.DateTimeField(default=django.utils.timezone.now)),
                ('ovrigInfo', models.CharField(blank=True, max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=124)),
                ('adress', models.CharField(max_length=124)),
                ('kontakt', models.CharField(max_length=124)),
            ],
        ),
        migrations.AddField(
            model_name='bokning',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Klient'),
        ),
    ]
