# Generated by Django 2.0.6 on 2018-06-11 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180610_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bokning',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bokning',
            name='pumpSlut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bokning',
            name='pumpStart',
            field=models.DateTimeField(),
        ),
    ]
