# Generated by Django 2.0.6 on 2018-06-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180611_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bokning',
            name='datum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bokning',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
