# Generated by Django 2.0.6 on 2018-06-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180613_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bokning',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bokning',
            name='pumpStr',
            field=models.IntegerField(blank=True, null=True, verbose_name='pump storlek:'),
        ),
    ]
