# Generated by Django 2.0.1 on 2018-06-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180616_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bokning',
            name='arbNr',
        ),
        migrations.RemoveField(
            model_name='bokning',
            name='bestalld',
        ),
        migrations.RemoveField(
            model_name='bokning',
            name='betongKvalite',
        ),
        migrations.RemoveField(
            model_name='bokning',
            name='betongLev',
        ),
        migrations.RemoveField(
            model_name='bokning',
            name='pump',
        ),
        migrations.RemoveField(
            model_name='bokning',
            name='pumpStr',
        ),
        migrations.RemoveField(
            model_name='bokning',
            name='referens',
        ),
        migrations.AlterField(
            model_name='bokning',
            name='littNr',
            field=models.CharField(max_length=124),
        ),
    ]
