# Generated by Django 2.0.6 on 2018-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bokning',
            name='pumpMng',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
