# Generated by Django 2.0.6 on 2018-08-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20180817_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bokning',
            name='pumpMng',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='targetMail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
